zuul:
  routes:
    get:
      path: /get/**
      url: http://127.0.0.1:9099
    my-service:
      path: /BESTBUY-WX/**
      serviceId: BESTBUY-WX
    images:
      path: /image/**
      url: http://httpbin.org/image